name: Scan real_DonaldJTrump Channel

on:
  schedule:
    - cron: "0 3 * * *"
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  scan:
    uses: ./.github/workflows/scan-only-template.yml
    with:
      channel: real_DonaldJTrump
      data_dir: real_DonaldJTrump
      depth: 5
      max_messages: 999
      max_channels: 999
    secrets: inherit
