name: Scan bannonwarroom Channel

on:
  schedule:
    - cron: "0 6 * * *"
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/06h-bannonwarroom.yml'
      - '.github/workflows/scan-only-template.yml'

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  scan:
    uses: ./.github/workflows/scan-only-template.yml
    with:
      channel: bannonwarroom
      data_dir: bannonwarroom
      depth: 2
      max_messages: 99
      max_channels: 999
    secrets: inherit
