name: Scan Channel Template

on:
  workflow_dispatch:
  workflow_call:
    inputs:
      channel:
        description: "Channel name to scan"
        required: true
        type: string
      data_dir:
        description: "Directory name for storing data (lowercase)"
        required: true
        type: string

permissions:
  contents: write

jobs:
  scan-channel:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Create .env file with secrets
        run: |
          echo "TELEGRAM_API_ID=${{ secrets.TELEGRAM_API_ID }}" >> .env
          echo "TELEGRAM_API_HASH=${{ secrets.TELEGRAM_API_HASH }}" >> .env
          echo "TELEGRAM_PHONE=${{ secrets.TELEGRAM_PHONE }}" >> .env
          echo "TELEGRAM_SESSION_STRING=${{ secrets.TELEGRAM_SESSION_STRING }}" >> .env

      - name: Run terrorscan for ${{ inputs.channel }}
        run: |
          python terrorscan.py deep-scan -c ${{ inputs.channel }} -d 9 -m 99 -mc 99 -o results
        continue-on-error: true

      - name: Setup git config
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"

      - name: Commit scan results to main branch
        run: |
          # Check if scan produced any results
          if [ ! -d "results" ] || [ -z "$(ls -A results 2>/dev/null)" ]; then
            echo "No scan results found for ${{ inputs.channel }}, skipping commit"
            exit 0
          fi

          # Create date-based directory structure
          YEAR=$(date +%Y)
          MONTH=$(date +%m)
          DAY=$(date +%d)
          TIMESTAMP=$(date +%H%M%S)
          DATE_DIR="data/${{ inputs.data_dir }}/${YEAR}/${MONTH}/${DAY}"
          TIMESTAMPED_DIR="${DATE_DIR}/${TIMESTAMP}"

          # Create timestamped directory
          mkdir -p "${TIMESTAMPED_DIR}"

          # Copy all scan results to timestamped directory
          cp -r results/* "${TIMESTAMPED_DIR}/"

          # Commit and push results
          git add data/${{ inputs.data_dir }}/
          if git diff --staged --quiet; then
            echo "No changes to commit"
          else
            git commit -m "Add ${{ inputs.channel }} scan results ${YEAR}-${MONTH}-${DAY} ${TIMESTAMP}"
            git push origin main || {
              echo "Push failed, attempting to pull and retry"
              git pull --rebase origin main
              git push origin main
            }
          fi
