name: Scan nickjfuentes Channel

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  scan:
    uses: ./.github/workflows/scan-template.yml
    with:
      channel: nickjfuentes
      data_dir: nickjfuentes
    secrets: inherit
