name: Scan nickjfuentes Channel

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  scan:
    uses: ./.github/workflows/scan-template.yml
    with:
      channel: nickjfuentes
      data_dir: nickjfuentes
    secrets: inherit
